-- Generated by tools/spann_bridge/generate_layout.py.
MAILBOX_BASE = 0x02030000
MAILBOX_SIZE = 0x1000
MAILBOX_MAGIC = 0x4D325741
MAILBOX_VERSION = 2
MAILBOX_STATES = { IDLE = 0, REQUEST_READY = 1, WAITING = 2, RESPONSE_READY = 3, EXECUTING = 4, ERROR = 5 }
MAILBOX_ACTIONS = { NONE = 0, BUILD = 1, UNIT = 2, END_TURN = 3, POWER = 4 }
MAILBOX_FIELDS = { magic = 0, version = 4, header_size = 6, session_id = 8, request_id = 12, state = 16, request_length = 20, response_length = 24, error_code = 28, response_session_id = 32, response_request_id = 36, frame_counter = 40, last_action = 44, request = 128, response = 2816, debug = 3072 }
MAILBOX_REQUEST = { capacity = 2688, snapshot_version = 0, width = 2, height = 3, mode = 4, map_id = 5, active_side = 6, ai_phase = 7, day = 8, global_state = 10, executor_state = 12, map_cells = 14, state_seed = 16, fog = 20, weather = 21, reserved_16 = 22, unit_plane = 32, property_plane = 1320, unit_records = 2608, unit_record_count = 256, unit_record_stride = 12, player_records = 5680, player_record_count = 5, player_record_stride = 60, special_hp_plane = 5980, file_length = 7268, external_unit_records_address = 33695364, external_player_records_address = 33698436, external_special_hp_address = 33720500 }
MAILBOX_RESPONSE = { capacity = 256, action = 0, unit_id = 1, dest_x = 2, dest_y = 3, command = 4, param0 = 5, param1 = 6, path_length = 7, building_x = 8, building_y = 9, unit_type = 10, reserved_0b = 11, path = 16, path_capacity = 12, state_seed = 96 }
