#!/usr/bin/env python3
"""Generate assembly, Python, and Lua mailbox constants from one JSON layout."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
LAYOUT_PATH = ROOT / "mod" / "mailbox_layout.json"


def _constant_name(prefix: str, name: str) -> str:
    return f"{prefix}_{name.upper()}"


def render_asm(layout: dict[str, object]) -> str:
    lines = ["/* Generated by tools/spann_bridge/generate_layout.py. */"]
    lines += [
        f".equ MAILBOX_BASE, 0x{int(layout['base']):08X}",
        f".equ MAILBOX_SIZE, 0x{int(layout['size']):X}",
        f".equ MAILBOX_MAGIC, 0x{int(layout['magic']):08X}",
        f".equ MAILBOX_VERSION, {int(layout['version'])}",
    ]
    for group, prefix in (("states", "MAILBOX_STATE"), ("actions", "MAILBOX_ACTION")):
        for name, value in layout[group].items():
            lines.append(f".equ {_constant_name(prefix, name)}, {int(value)}")
    for name, value in layout["fields"].items():
        lines.append(f".equ {_constant_name('MAILBOX_OFF', name)}, 0x{int(value):X}")
    for name, value in layout["request"].items():
        lines.append(f".equ {_constant_name('REQUEST', name)}, 0x{int(value):X}")
    for name, value in layout["response"].items():
        lines.append(f".equ {_constant_name('RESPONSE', name)}, 0x{int(value):X}")
    return "\n".join(lines) + "\n"


def render_python(layout: dict[str, object]) -> str:
    return (
        '"""Load the shared local-AW2-agent mailbox definition."""\n\n'
        "from __future__ import annotations\n\n"
        "import json\n"
        "from pathlib import Path\n\n"
        "LAYOUT_PATH = Path(__file__).resolve().parents[2] / \"mod\" / \"mailbox_layout.json\"\n"
        "LAYOUT = json.loads(LAYOUT_PATH.read_text(encoding=\"utf-8\"))\n"
        'BASE = int(LAYOUT["base"])\n'
        'SIZE = int(LAYOUT["size"])\n'
        'MAGIC = int(LAYOUT["magic"])\n'
        'VERSION = int(LAYOUT["version"])\n'
        'STATES = LAYOUT["states"]\n'
        'ACTIONS = LAYOUT["actions"]\n'
        'FIELDS = LAYOUT["fields"]\n'
        'REQUEST = LAYOUT["request"]\n'
        'RESPONSE = LAYOUT["response"]\n'
    )


def render_lua(layout: dict[str, object]) -> str:
    def table(values: dict[str, object]) -> str:
        body = ", ".join(f"{key} = {int(value)}" for key, value in values.items())
        return "{ " + body + " }"

    return "\n".join(
        [
            "-- Generated by tools/spann_bridge/generate_layout.py.",
            f"MAILBOX_BASE = 0x{int(layout['base']):08X}",
            f"MAILBOX_SIZE = 0x{int(layout['size']):X}",
            f"MAILBOX_MAGIC = 0x{int(layout['magic']):08X}",
            f"MAILBOX_VERSION = {int(layout['version'])}",
            f"MAILBOX_STATES = {table(layout['states'])}",
            f"MAILBOX_ACTIONS = {table(layout['actions'])}",
            f"MAILBOX_FIELDS = {table(layout['fields'])}",
            f"MAILBOX_REQUEST = {table(layout['request'])}",
            f"MAILBOX_RESPONSE = {table(layout['response'])}",
            "",
        ]
    )


def generated_outputs() -> dict[Path, str]:
    layout = json.loads(LAYOUT_PATH.read_text(encoding="utf-8"))
    return {
        ROOT / "mod" / "generated" / "mailbox.inc": render_asm(layout),
        ROOT / "tools" / "spann_bridge" / "mailbox_layout.py": render_python(layout),
        ROOT / "tools" / "mgba" / "mailbox_layout.lua": render_lua(layout),
    }


def generate(*, check: bool = False) -> None:
    outputs = generated_outputs()
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"generated mailbox constants are stale: {path}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    generate(check=parser.parse_args().check)
